const data = {
    products: [
      {
        _id: '1',
        name: 'Alternateur',
        category: 'Electrique',
        image: '/images/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Valeo',
        rating: 4.5,
        numReviews: 10,
        description: 'Electrique system',
      },
      {
        _id: '2',
        name: 'Triangle Amortissement',
        category: 'Systeme Amortissement',
        image: '/images/p2.jpg',
        price: 150,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'ABS system',
      },
      {
        _id: '3',
        name: 'Kit Amortisseurs',
        category: 'Systeme Amortissement',
        image: '/images/p3.jpg',
        price: 110,
        countInStock: 0,
        brand: 'Valeo',
        rating: 4.8,
        numReviews: 17,
        description: 'ABS System',
      },
      {
        _id: '4',
        name: 'Kit Embrayage',
        category: 'Transmission',
        image: '/images/p4.jpg',
        price: 500,
        countInStock: 15,
        brand: 'Valeo',
        rating: 4.5,
        numReviews: 14,
        description: 'Gear',
      },
      {
        _id: '5',
        name: 'Disque de frein',
        category: 'Systeme de freinage',
        image: '/images/p5.jpg',
        price: 110,
        countInStock: 5,
        brand: 'Valeo',
        rating: 4.5,
        numReviews: 10,
        description: 'ABS system',
      },
      {
        _id: '6',
        name: 'Filtre huile',
        category: 'Valeo',
        image: '/images/p6.jpg',
        price: 50,
        countInStock: 12,
        brand: 'Valeo',
        rating: 4.5,
        numReviews: 15,
        description: 'Entretien',
      },
    ],
  };
  export default data;